services:
  - type: web
    name: taller-pacheco-cotizaciones
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
